src/Entity/Formation.php
<?php

namespace App\Entity;

use App\Repository\FormationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FormationRepository::class)
 * @ORM\Table(name="formations")
 */
class Formation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="integer")
     */
    private $Duree;
    /**
     * @ORM\ManyToOne(targetEntity="Ecole", inversedBy="formations")
     * @ORM\JoinColumn(name="ecole_id", referencedColumnName="id")
     */
    private $ecole;
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getDuree(): ?int
    {
        return $this->Duree;
    }

    public function setDuree(int $Duree): self
    {
        $this->Duree = $Duree;

        return $this;
    }
    /**
     * @return Ecole|null
     */
    public function getEcole(): ?Ecole
    {
        return $this->ecole;
    }

    /**
     * @param Ecole|null $ecole
     */
    public function setEcole(?Ecole $ecole): void
    {
        $this->ecole = $ecole;
    }
    
}

src/Form/FormationType.php
<?php

namespace App\Form;

use App\Entity\Formation;
use App\Entity\Ecole;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FormationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Nom', TextType::class, [
                'label' => 'Nom de la formation',
                'attr' => ['class' => 'form-control'],
            ])
            ->add('Duree', TextType::class, [
                'label' => 'Duree de la formation',
                'attr' => ['class' => 'form-control'],
            ])
            // Ajouter le champ de sélection pour l'école
            ->add('ecole', EntityType::class, [
                'class' => Ecole::class,
                'label' => 'École',
                'attr' => ['class' => 'form-control'],
                'choice_label' => 'Nom', 
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Formation::class,
        ]);
    }
}

src/Controller/FormationController.php
<?php

namespace App\Controller;
use App\Entity\Formation;
use App\Form\FormationType;
use App\Entity\Ecole;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class FormationController extends AbstractController
{
    /**
     * @Route("/formation", name="app_formation")
     */
    public function index(): Response
    {
        $data=$this->getDoctrine()
            ->getRepository(Formation::class)
            ->createQueryBuilder('f')
            ->leftJoin('f.ecole', 'e') // Jointure avec l'entité Ecole
            ->addSelect('e') 
            ->getQuery()
            ->getResult();
        return $this->render('formation/index.html.twig', [
            'data' => $data,
        ]);
    }
    /**
     * @Route("/formation/new", name="formation_new")
     */
    public function new(Request $request): Response
    {
        $formation = new Formation();
        $form = $this->createForm(FormationType::class, $formation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            $ecole = $formation->getEcole();
            if ($ecole) {
        
                $formation->setEcole($ecole);

                $entityManager->persist($formation);
                $entityManager->flush();

                // $this->addFlash('success', 'Nouvelle formation ajoutée avec succès');

                return $this->redirectToRoute('app_formation'); // Rediriger vers la liste des formations, ajustez cela en fonction de votre structure de routes
            } else {

                $this->addFlash('error', 'Veuillez sélectionner une école.');
            }
        }

        return $this->render('formation/create.html.twig', [
            'form' => $form->createView(),
        ]);
    }
    /**
     * @Route("/formation/update{id}", name="formation_update")
     */
    public function update(Request $request,int $id): Response
    {
        $formation = $this->getDoctrine()->getRepository(Formation::class)->find($id);
        $form = $this->createForm(FormationType::class, $formation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();

            $ecole = $formation->getEcole();

            if ($ecole) {
                $formation->setEcole($ecole);
                $entityManager->persist($formation);
                $entityManager->flush();

                $this->addFlash('success', 'Nouvelle formation ajoutée avec succès');

                return $this->redirectToRoute('app_formation'); 
            } else {
        
                $this->addFlash('error', 'Veuillez sélectionner une école.');
            }
        }
        return $this->render('formation/update.html.twig', [
            'form' => $form->createView(),
            'FormationId'=> $id,
        ]);
    }
     /**
    * @Route("formation/delete{id}",name="formation_delete")
     */
    public function delete(Request $request,int $id): Response{

        $formation= $this->getDoctrine()->getRepository(Formation::class)->find($id);
            $em =$this->getDoctrine()->getManager(); 
            $em->remove($formation);
            $em->flush();
    
            return $this->redirectToRoute('app_formation');
        }
}

templates/formation/create.html.twig
{% extends 'base.html.twig' %}

{% block content %}
<style>
  h3{
    text-align:center;
    color:blue;
  }
  button{
    margin-top: 30px
  }
</style>  
<div class="container">
  <div class="row">
    <h3 class="mt-5 mb-5">Ajouter Une Formation</h3>
    {% for message in app.flashes('notice') %}
     <div class="alert alert-success">
       {{ message }}
     </div>
    {% endfor %}
    <div class="col-md-6 offset-md-3">
        {{ form_start(form) }}
        <div class="form-group">
            {{ form_label(form.Nom) }}
            {{ form_widget(form.Nom, {'attr': {'class': 'form-control'}}) }}
        </div>
        <div class="form-group">
            {{ form_label(form.Duree) }}
            {{ form_widget(form.Duree, {'attr': {'class': 'form-control'}}) }}
        </div>
        <div class="form-group">
            {{ form_label(form.ecole) }}
            {{ form_widget(form.ecole, {'attr': {'class': 'form-control'}}) }}
        </div>
        <div class="form-group">
            <button class="btn btn-success btn-block">Ajouter</button>
        </div>
        {{ form_end(form) }}
    </div>
  </div>  
</div>  
{% endblock %}

templates/formation/index.html.twig
{% extends 'base.html.twig' %} {% block content %}
<style>
  h2 {
    margin: 30px 0;
    text-align: center;
  }
</style>

<div class="container">
  <h2>List des formation</h2>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Nom</th>
        <th scope="col">Duree</th>
        <th scope="col">Ecole</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      {% for c in data %}
      <tr>
        <th scope="row">{{ c.id }}</th>
        <td>{{ c.Nom }}</td>
        <td>{{ c.Duree }}</td>
        <td>{{ c.ecole.nom }}</td>
        <td>
          <a class="btn btn-info" href="{{ path('formation_update', { id: c.id }) }}">Modifier</a>
          <a class="btn btn-danger" onclick="return confirm('Etes vous sure?')" href="{{ path('formation_delete', { id: c.id }) }}" >Supprimer</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

templates/formation/update.html.twig
{% extends 'base.html.twig' %}

{% block content %}
<style>
  h3{
    text-align:center;
    color:blue;
  }
  button{
    margin-top: 30px
  }
</style>  
<div class="container">
  <div class="row">
    <h3 class="mt-5 mb-5">Modifier Une Formation</h3>
    <div class="col-md-6 offset-md-3">
        {{ form_start(form) }}
        <input class="form-control id" disabled value="{{ FormationId }}"></input>
        <div class="form-group">
            {{ form_label(form.Nom) }}
            {{ form_widget(form.Nom, {'attr': {'class': 'form-control'}}) }}
        </div>
        <div class="form-group">
            {{ form_label(form.Duree) }}
            {{ form_widget(form.Duree, {'attr': {'class': 'form-control'}}) }}
        </div>
        <div class="form-group">
            {{ form_label(form.ecole) }}
            {{ form_widget(form.ecole, {'attr': {'class': 'form-control'}}) }}
        </div>
        <div class="form-group">
            <button class="btn btn-success btn-block">Modifier</button>
        </div>
        {{ form_end(form) }}
    </div>
  </div>  
</div>  
{% endblock %}