src/Entity/Ecole.php
<?php

namespace App\Entity;

use App\Repository\EcoleRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

/**
 * @ORM\Entity(repositoryClass=EcoleRepository::class)
 * @ORM\Table(name="ecoles")
 */
class Ecole
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")

     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Adresse;
    /**
     * @ORM\OneToMany(targetEntity="Formation", mappedBy="ecole")
     */
    private $formations;
    public function __construct()
    {
        $this->formations = new ArrayCollection();
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }
    
    public function setAdresse(string $Adresse): self
    {
        $this->Adresse = $Adresse;

        return $this;
    }
     /**
     * @return Collection|Formation[]
     */
    public function getFormations(): Collection
    {
        return $this->formations;
    }
}

src/Entity/Formation.php
<?php

namespace App\Entity;

use App\Repository\FormationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=FormationRepository::class)
 * @ORM\Table(name="formations")
 */
class Formation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="integer")
     */
    private $Duree;
    /**
     * @ORM\ManyToOne(targetEntity="Ecole", inversedBy="formations")
     * @ORM\JoinColumn(name="ecole_id", referencedColumnName="id")
     */
    private $ecole;
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getDuree(): ?int
    {
        return $this->Duree;
    }

    public function setDuree(int $Duree): self
    {
        $this->Duree = $Duree;

        return $this;
    }
    /**
     * @return Ecole|null
     */
    public function getEcole(): ?Ecole
    {
        return $this->ecole;
    }

    /**
     * @param Ecole|null $ecole
     */
    public function setEcole(?Ecole $ecole): void
    {
        $this->ecole = $ecole;
    }
    
}

src/Form/EcoleType.php
<?php

namespace App\Form;
use App\Controller\FormationController;
use App\Entity\Ecole;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EcoleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Nom')
            ->add('Adresse')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Ecole::class,
        ]);
    }
}

src/Controller/EcoleController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use App\Form\EcoleType;
use App\Entity\Ecole;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\ORM\EntityManagerInterface;

class EcoleController extends AbstractController
{
    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager = $entityManager;
    }
     /**
     * @Route("/", name="index")
     */
    public function page_dacceuil():Response
    {
        return $this->render('index.html.twig');
    }
    /**
     * @Route("/ecole", name="app_ecole")
     */
    public function index(): Response
    {
        $data=$this->getDoctrine()->getRepository(Ecole::class)->findAll();
        return $this->render('ecole/index.html.twig', [
            'data' => $data,
        ]);
    }
     /**
    * @Route("/ecole/create",name="Ecole_new")
     */
    public function create(Request $request){
       $ecole= new Ecole();
       $form=$this->createForm(EcoleType::class,$ecole);
       $form->handleRequest($request);
       if ($form->isSubmitted() && $form->isValid()) {
        $em= $this->getDoctrine()->getManager();
        $em->persist($ecole);
        $em->flush();
        $this->addFlash('notice','ecole ajouté avec succes');
        return $this->redirectToRoute('app_ecole');  
    }
       return $this->render('ecole/create.html.twig', [
        'form' => $form->createView(),
    ]);
     }
     /**
    * @Route("ecole/update{id}",name="Ecole_update")
     */
    public function update(request $request,int $id){
       $ecole= $this->getDoctrine()->getRepository(Ecole::class)->find($id);
       $form=$this->createForm(EcoleType::class,$ecole);
       $form->handleRequest($request);
       if ($form->isSubmitted() && $form->isValid()) {
        $em= $this->getDoctrine()->getManager();
        $em->persist($ecole);
        $em->flush();
        // $this->addFlash('notice','modification effectuée avec succes');
        return $this->redirectToRoute('app_ecole');  
       }
       return $this->render('ecole/update.html.twig', [
        'form' => $form->createView(),
        'ecoleId'=> $id
    ]);

    }
     /**
    * @Route("ecole/delete{id}",name="Ecole_delete")
     */
    public function delete($id){
    // Récupérer l'école à supprimer
    $ecole= $this->getDoctrine()->getRepository(Ecole::class)->find($id);
    if (!$ecole) {
        throw $this->createNotFoundException('L\'école n\'existe pas');
    }
    $formations = $ecole->getFormations();
    foreach ($formations as $formation) {
        
        $this->entityManager->remove($formation);
    }
        $data = $this->getDoctrine()->getRepository(Ecole::class)->find($id);
        $em =$this->getDoctrine()->getManager(); 
        $em->remove($data);
        $em->flush();

        // $this->addFlash('notice','suppresion effectuée avec succes');
        return $this->redirectToRoute('app_ecole');
    }
    /**
     * @Route("/recherche_formation_par_ecole", name="recherche_formation_par_ecole")
     */
    public function rechercheFormationParEcole(Request $request): Response
    {
        // Récupérez le nom de l'école à partir de la requête (à ajuster selon votre logique)
        $nomEcole = $request->query->get('ecole_nom');
        $ecole="";
        $formations=null;
        if ($nomEcole !== null) {
         
        $ecoleRepository = $this->getDoctrine()->getRepository(Ecole::class);
        $ecole = $this->getDoctrine()->getRepository(Ecole::class)->findByNom($nomEcole);

        $formations = $ecole->getFormations();
        }
        return $this->render('ecole/ecole_form.html.twig', [
            'ecole' =>  $ecole ,
            'formations' => $formations,
        ]);
    
    }
    
}

templates/ecole/create.html.twig
{% extends 'base.html.twig' %}
{% block content %}
<style>
  h3{
    text-align:center;
    color:blue;
  }
  button{
    margin-top: 30px
  }
</style>  
<div class="container">
  <div class="row">
    <h3 class="mt-5 mb-5">Ajouter Une Ecole</h3>
    {% for message in app.flashes('notice')%}
     <div class="alert alert-success">
       {{ message }}
     </div>
    {% endfor %}
    <div class="col-md-6 offset-md-3">
  {{form_start(form)}}
    <div class="form-goup">
      {{form_label(form.Nom)}}
      {{form_widget(form.Nom,{'attr':{'class':'form-control'}})}}
    </div>
    <div class="form-group">
      {{form_label(form.Adresse)}}
      {{form_widget(form.Adresse,{'attr':{'class':'form-control'}})}}
    </div> 
    <div class="form-group">
      <button class="btn btn-success btn-block" >Ajouter</button>
    </div>
      {{form_end(form)}}
    </div>
  </div>  
</div>  
{% endblock %}


templates/ecole/ecole_form.html.twig
{% extends 'base.html.twig' %}

{% block content %}
    <div class="container c1 mt-2">
        <form action="{{ path('recherche_formation_par_ecole') }}" method="get">
            <label for="ecole">Nom de l'école:</label>
            <input type="text" id="ecole" name="ecole_nom">
            <button class="btn btn-info" type="submit">Rechercher</button>
        </form>

        {% if ecole %}
            <div class="card">
                <div class="card-header">Ecole </div>
                <div class="card-body" mt-5>
                    <table class="table">
                        <thead>
                            <tr>
                                <th>ID</th>
                                <th>Nom</th>
                                <td>Adresse</td>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>{{ ecole.id }}</td>
                                <td>{{ ecole.nom }}</td>
                                <td>{{ ecole.adresse }}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>

            {% if formations is not empty %}
                <h3>Formations disponibles dans l'école:</h3>
                <table class="table">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Nom</th>
                            <th>Durée</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for formation in formations %}
                            <tr>
                                <td>{{ formation.id }}</td>
                                <td>{{ formation.nom }}</td>
                                <td>{{ formation.duree }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <div class="card">
                    <p style="text-align: center">Aucune formation trouvée pour l'école spécifiée.</p>
                </div>
            {% endif %}
        {% endif %}
    </div>
    {% endblock %}

templates/ecole/index.html.twig
{% extends 'base.html.twig' %} {% block content %}
<style>
  h2 {
    margin: 30px 0;
    text-align: center;
  }
</style>

<div class="container">
  <h2>List des ecoles</h2>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Nom</th>
        <th scope="col">Adresse</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      {% for c in data %}
      <tr>
        <th scope="row">{{ c.id }}</th>
        <td>{{ c.Nom }}</td>
        <td>{{ c.Adresse }}</td>
        <td>
          <a class="btn btn-info" href="{{ path('Ecole_update', { id: c.id }) }}"
            >Modifier</a
          >
          <a class="btn btn-danger" onclick="return confirm('Etes vous sure?')" href="{{ path('Ecole_delete', { id: c.id }) }}" onclick="deleteEcole({{ c.id }})"
            >Supprimer</a>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock %}

templates/ecole/update.html.twig
{% extends 'base.html.twig' %}
{% block content %}
<style>
  h3{
    text-align:center;
    color:blue;
  }
  button{
    margin-top: 30px
  }
  .id{
    text-align:center;
  }
</style>  
<div class="container">
  <div class="row">
    <h3 class="mt-5 mb-5">Modifier Une Ecole</h3>
    {% for message in app.flashes('notice')%}
     <div class="alert alert-success">
       {{ message }}
     </div>
    {% endfor %}
    <div class="col-md-6 offset-md-3">
  {{form_start(form)}}
    <input class="form-control id" disabled value="{{ ecoleId }}"></input>
    <div class="form-goup">
      {{form_label(form.Nom)}}
      {{form_widget(form.Nom,{'attr':{'class':'form-control'}})}}
    </div>
    <div class="form-group">
      {{form_label(form.Adresse)}}
      {{form_widget(form.Adresse,{'attr':{'class':'form-control'}})}}
    </div> 
    <div class="form-group">
      <button class="btn btn-success btn-block" >Modifier</button>
    </div>
      {{form_end(form)}}
    </div>
  </div>  
</div>  
{% endblock %}
